### ISSUE TITLE
Cognito and Dynamo?

### ISSUE THREAD

**Issue by brennanerbz** [awslabs/startup-kit-nodejs#1]
Why not use the other AWS services Cognito and DynamoDB?

**Comment by rabowskyb** [comment]
There are plans to integrate Cognito eventually.  Cognito provides JSON web keys, which in turn can be used by the Passport module as an alternative to a the secret in the config file.  The implementation will be presented as an option that can be chosen from the config file so that the workload can be run with the regular secret or JSON web keys from Cognito.  

Regarding DynamoDB, for this particular Startup Kit workload, we're focusing instead on relational databases.  We've used DynamoDB in the Startup Kit's serverless workload, which can be found at https://github.com/awslabs/startup-kit-serverless-workload.
